version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/go3mf.bash"
    - sh -c "go run . completion zsh > completions/_go3mf"
    - sh -c "go run . completion fish > completions/go3mf.fish"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/philipparndt/go3mf/version.Version={{.Version}} -X github.com/philipparndt/go3mf/version.GitCommit={{.Commit}} -X github.com/philipparndt/go3mf/version.BuildDate={{.Date}}

release:
  github:
    owner: philipparndt
    name: go3mf

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [zip]
    files:
      - completions/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew:
  - name: go3mf
    repository:
      owner: philipparndt
      name: homebrew-go3mf
      branch: main
      pull_request:
        enabled: false
        draft: false

    commit_author:
      name: Philipp Arndt
      email: opensource@rnd7.de

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    directory: Formula

    homepage: "https://github.com/philipparndt/go3mf"

    description: "3D model file combiner and SCAD renderer"

    license: "Apache-2.0"

    install: |
      bin.install "go3mf"
      bash_completion.install "completions/go3mf.bash" => "go3mf"
      zsh_completion.install "completions/_go3mf"
      fish_completion.install "completions/go3mf.fish"
